apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-talk
  labels:
    app: tech-talk-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tech-talk-web
  template:
    metadata:
      labels:
        app: tech-talk-web
    spec:
      containers:
      - name: tech-talk-web
        image: 243060292047.dkr.ecr.eu-west-1.amazonaws.com/grid-extras:tech-talk-dev--0410212029
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: tech-talk
  labels:
    app: tech-talk-web
spec:
  selector:
    app: tech-talk-web
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.org/proxy-connect-timeout: 30s
    nginx.org/proxy-read-timeout: 20s
  labels:
    app: tech-talk-web
  name: tech-talk
spec:
  rules:
  - host: tech-talk.sandbox.grid2.maf.ae
    http:
      paths:
      - backend:
          serviceName: tech-talk
          servicePort: 80
        path: /(.*)
        pathType: ImplementationSpecific